export const gitEmojiMap = [
  ['art', '🎨'],
  ['bug', '🐞'],
  ['docs', '📚'],
  ['style', '💄'],
  ['refactor', '♻️'],
  ['perf', '🚀'],
  ['optimize', '🔥'],
  ['test', '🧪'],
  ['ci', '🔄'],
  ['i18n', '🌍'],
  ['feat', '🆕'],
  ['docs', '📝'],
  ['chore', '🧹'],
  ['other', '❓'],
  ['typescript', '🤖'],
  ['remove ', '🗑️'],
  ['hotfix', '🚑'],
  ['newFeature', '✨'],
  ['startProject', '🎉'],
  ['upgradeDeps', '⬆️'],
  ['downgradeDeps', '⬇️'],
  ['addDeps', '➕'],
  ['removeDeps', '➖'],
  ['fixBug', '🐛'],
  ['refactor', '💡'],
  ['optimize', '🔥'],
  ['fixTypos', '✏️'],
  ['build', '🔧'],
  ['moveResources', '🚚 '],
  ['changeLicense', '📄']
];
